name: Deploy Contact Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Navigate to Worker directory
        working-directory: Cloudflare/contact-worker
        run: |
          echo "Deploying Cloudflare Worker..."

      - name: Publish Worker
        working-directory: Cloudflare/contact-worker
        run: wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}