name: Deploy Contact Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    name: Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run behavioural tests
        working-directory: Cloudflare/contact-worker
        run: |
          npm install
          npm run test

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Navigate to Worker directory
        working-directory: Cloudflare/contact-worker
        run: |
          echo "Deploying Cloudflare Worker..."
    
      - name: Publish Contact Worker
        working-directory: Cloudflare/contact-worker
        run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Publish Portfolio Insight Worker
        working-directory: Cloudflare/portfolio-insight-worker
        run: |
          npm install
          npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}